export const LOGIN_ORG_START = "LOGIN_ORG_START";
export const LOGIN_ORG_SUCCESS = "LOGIN_ORG_SUCCESS";
export const LOGIN_ORG_ERROR = "LOGIN_ORG_ERROR";
export const LOGOUT_ORG = "LOGOUT_ORG";
export const UPDATE_ORG_POSITIONS = "UPDATE_ORG_POSITIONS";

export const LOGIN_IND_START = "LOGIN_IND_START";
export const LOGIN_IND_SUCCESS = "LOGIN_IND_SUCCESS";
export const LOGIN_IND_ERROR = "LOGIN_IND_ERROR";
export const LOGOUT_IND = "LOGOUT_IND";

export const UPDATE_POSITIONS = "UPDATE_POSITIONS";
